# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e291faab9a38fced5eb5a28314ee1f0870a2e1990528e949675779d81837d907156df4bbe2cda6197a42248b91dabea4fe0bf2c674cbfee9a9700d459d6e7b6

test:
  secret_key_base: 6ca823744f7ccb11f5f200da9a45ec91c33abe23ce1cf33dd6a21bc804b01a37797c6ed311318a9c98b7646c8a35898c55b88923ac14162919d2e397cd5a0f06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
